services:
  gateway:
    build: ./gateway
    ports:
      - "8010:80"
    environment:
      - SECRET_KEY="${SECRET_KEY}"
    depends_on:
      - backend
    volumes:
      - ./gateway/default.conf:/etc/nginx/conf.d/default.conf:ro
      
    command: ["/usr/local/openresty/bin/openresty", "-g", "env SECRET_KEY; daemon off;"]

  backend:
    build: ./test_api
    ports:
      - "8011:8011"
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8011"]
