server {
    listen 80;
    server_name sandori.kr sandol.sio2.kr localhost sandol.house.sio2.kr fastapi.house.sio2.kr 10.10.10.102;
    resolver 127.0.0.11 valid=10s ipv6=off;

    # 라우트 함수들
    include /etc/nginx/conf.d/routes/*.conf;
}
